### ISSUE TITLE
fix bug when indexing that appears when indexing wikipedia without positions

### ISSUE THREAD

**Issue by fulmicoton** [tantivy-search/tantivy-cli#7]
Cause is unidentified. It could be in tantivy or in tantivy-cli.

**Comment by watreyoung** [comment]
Is the bug fixed now? I just met the same issue last week. 
P.S. If one item is assigned as index without positions, the index will just include the tokenized item? 

I have another question with tantivy-cli.
**What can I achieve the original inverted index with tantivy-cli?**
For instance, I have a body "I like English and I like reading books" and two keywords "English" - "books". What can I do for the indexes with indefinite number? It means that if I search English, I will find the body that include English. If I search Book, I will find the body that include Book. If I search English and Book, the body "I like English and I like reading books" should be returned first rather than the body that may onlu include English or Book.

Looking forward to your reply. Thanks!
